apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-redis
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0312ae4a1f428ac65 #ID del EFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-redis
  namespace: netbox-actividad3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 8Gi
