apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: netbox-actividad3
  labels:
    k8s-app: netbox
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
  selector:
    k8s-app: netbox
