apiVersion: v1
kind: Secret
metadata:
  name: netbox-secrets
  namespace: netbox-actividad3
type: Opaque
stringData:
  db_password: "netbox"
  db_user: "netbox"
  db_name: "netbox"
  secret_key: "jodYA_pDxGjxKe6aluFf3Mijqw6-GjDxJM8hHDUKj4yisYVhhFlO-M68Kp1M7lXOswyEFkI0tkuXUCzpXg7qmw"
  superuser_password: "netbox"
